import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:friendslocation/data/local/sharedpreference/mypref.dart';
import 'package:friendslocation/getX/state_manager/controller/getx_controller.dart';
import 'package:friendslocation/model/friend_model.dart';
import 'package:get/get.dart';
import 'package:uuid/uuid.dart';
import '../util/app_lat_long.dart';
import '../util/location_service.dart';
import '../util/theme_change.dart';

class EnterNameScreen extends StatelessWidget {
  EnterNameScreen({super.key});

  AppLatLong? location;

  Future<void> fetchCurrentLocation() async {
    const defLocation = MoscowLocation();
    try {
      location = await LocationService().getCurrentLocation();
    } catch (_) {
      location = defLocation;
    }
    // _moveToCurrentLocation(location.lat,location.long);
  }

  Future<void> _initPermission() async {
    if (!await LocationService().checkPermission()) {
      await LocationService().requestPermission();
    }
    await fetchCurrentLocation();
  }

  @override
  Widget build(BuildContext context) {



    _initPermission();
    fetchCurrentLocation();
    Size size = MediaQuery.of(context).size;



    var uuid = Uuid.NAMESPACE_X500;
    var controller = TextEditingController();
    final getxcontroller = Get.find<EnterNameController>();
    return Scaffold(
      body: Stack(children: [
        // Padding(
        //   padding: const EdgeInsets.only(top: 38.0,left: 250),
        //   child: InkWell(
        //     onTap: () {
        //       Get.toNamed(
        //         "/mapscreen",
        //       );
        //     },
        //     child: const Card(
        //       child: Text("All friends",style: TextStyle(
        //         fontSize: 20
        //       ),),
        //     ),
        //   ),
        // ),
        // Padding(
        //   padding: const EdgeInsets.only(top: 38.0),
        //   child: Column(
        //     children: [
        //       Text(
        //         "Change Theme",
        //         style: TextStyle(fontSize: size.height * 0.02),
        //       ),
        //       Obx(
        //         () => Switch(
        //           value: getxcontroller.currentTheme.value == ThemeMode.dark,
        //           onChanged: (value) {
        //             getxcontroller.switchTheme();
        //             Get.changeThemeMode(getxcontroller.currentTheme.value);
        //           },
        //           activeColor: CustomTheme.white,
        //         ),
        //       ),
        //     ],
        //   ),
        // ),
        Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Center(
                child: Image.asset("assets/btn.png", height: 160, width: 160)),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 18.0),
              child: TextField(
                decoration: const InputDecoration(
                  labelText: 'Enter your name',
                  hintText: 'Type something...',
                  // You can add more decoration properties as needed
                ),
                controller: controller,
                onChanged: (text) {
                  controller.text = text;
                  MyPref.saveName(controller.text);
                },
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(top: 18.0),
              child: ElevatedButton(
                  onPressed: () {
                    getxcontroller.sendLocation(Autogenerated(
                        "${uuid}${controller.text} ",
                        MyPref.getName(),
                        location?.lat,
                        location?.long));
                    Get.toNamed(
                      "/homepage",
                    );
                  },
                  child: Text("Enter name")),
            )
          ],
        ),
      ]),
    );
  }
}
