import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:friendslocation/data/local/sharedpreference/mypref.dart';
import 'package:friendslocation/getX/state_manager/controller/home_page_controller.dart';
import 'package:friendslocation/model/friend_model.dart';
import 'package:get/get.dart';
import 'package:get/get_core/src/get_main.dart';
import 'package:uuid/uuid.dart';

import '../getX/state_manager/controller/getx_controller.dart';
import '../util/app_lat_long.dart';
import '../util/location_service.dart';
import '../util/theme_change.dart';

class HomePage extends StatelessWidget {
  HomePage({super.key});

  AppLatLong? location;

  Future<void> fetchCurrentLocation() async {
    const defLocation = MoscowLocation();
    try {
      location = await LocationService().getCurrentLocation();
    } catch (_) {
      location = defLocation;
    }
    // _moveToCurrentLocation(location.lat,location.long);
  }
  Future<void> _initPermission() async {
    if (!await LocationService().checkPermission()) {
      await LocationService().requestPermission();
    }
    await fetchCurrentLocation();
  }

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    final getxcontroller = Get.find<HomePageController>();
    var uuid = Uuid.NAMESPACE_X500;
  _initPermission();
    fetchCurrentLocation();

    return Scaffold(
      body: Align(
        alignment: Alignment.center,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Padding(
              padding: const EdgeInsets.only(top: 38.0),
              child: Column(
                children: [
                  Text(
                    "Change Theme",
                    style: TextStyle(fontSize: size.height * 0.02),
                  ),
                  Obx(
                    () => Switch(
                      value:
                          getxcontroller.currentTheme.value == ThemeMode.dark,
                      onChanged: (value) {
                        getxcontroller.switchTheme();
                        Get.changeThemeMode(getxcontroller.currentTheme.value);
                      },
                      activeColor: CustomTheme.white,
                    ),
                  ),
                ],
              ),
            ),
            InkWell(
              onTap: () {
                Get.toNamed(
                  "/mapscreen",
                );
              },
              child: const Card(
                child: Text(
                  "All friends",
                  style: TextStyle(fontSize: 20),
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(top: 28.0),
              child: InkWell(
                onTap: () {
                  print(
                      "###################################################################${uuid}${MyPref.getName()}");
                  print("lat==${location?.lat}");
                  print("long==${location?.long}");
                  getxcontroller.updateLocation(Autogenerated(
                      "$uuid${MyPref.getName()}",
                      MyPref.getName(),
                      location?.lat ,
                      location?.long));
                },
                child: const Card(
                  child: Text(
                    "update location",
                    style: TextStyle(fontSize: 20),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
