import 'package:flutter/material.dart';
import 'package:friendslocation/repository/repository.dart';
import 'package:get/get.dart';

import '../../../model/friend_model.dart';

class EnterNameController extends GetxController {
  final repository = AppRepository();

  void sendLocation(Autogenerated friendModel) async {
    await repository.sendlocation(friendModel);
  }





}
