import 'package:friendslocation/repository/repository.dart';
import 'package:get/get.dart';

import '../../../model/friend_model.dart';

class EnterNameController extends GetxController {
  final repository = AppRepository();

  void sendLocation(Autogenerated friendModel) async {
    await repository.sendlocation(
        friendModel.mapId ?? "",
        friendModel.name ?? "",
        friendModel.late ?? 0,
        friendModel.long ?? 0);
  }
}
