import 'package:flutter/material.dart';
import 'package:friendslocation/repository/repository.dart';
import 'package:get/get.dart';

import '../../../model/friend_model.dart';

class EnterNameController extends GetxController {
  final repository = AppRepository();

  void sendLocation(Autogenerated friendModel) async {
    await repository.sendlocation(friendModel.mapId ?? "",
        friendModel.name ?? "", friendModel.late ?? 0, friendModel.long ?? 0);
  }

  Rx<ThemeMode> currentTheme = ThemeMode.system.obs;

  // function to switch between themes
  void switchTheme() {
    currentTheme.value = currentTheme.value == ThemeMode.light
        ? ThemeMode.dark
        : ThemeMode.light;
  }
}
