import 'package:flutter/material.dart';
import 'package:friendslocation/model/friend_model.dart';
import 'package:friendslocation/repository/repository.dart';
import 'package:get/get.dart';

class HomePageController extends GetxController {
  final apprepository = AppRepository();

  void updateLocation(Autogenerated friendModel) async {
    await apprepository.updateLocation(friendModel);
  }

  Rx<ThemeMode> currentTheme = ThemeMode.system.obs;

  // function to switch between themes
  void switchTheme() {
    currentTheme.value = currentTheme.value == ThemeMode.light
        ? ThemeMode.dark
        : ThemeMode.light;
  }
}
