import 'package:get/get.dart';

import '../../../model/friend_model.dart';
import '../../../repository/repository.dart';

class MapScreenGetXController extends GetxController {
  final repository = AppRepository();
  List<Autogenerated> list = [];

  void getAllFriends() async {
    var resualt=await repository.getFriendLocation();
    list=resualt;
  }
}
